<script>
    export let questionID;
    import Answer from "./Answer.svelte";
    import PostAnswerButtonModal from "./PostAnswerButtonModal.svelte";
    import { getCourseQuestionAnswers, getQuestion } from "../services/APIService";
    import viewport from '../services/useViewportAction';
    import {onMount} from "svelte";
    import Upvote from "./Upvote.svelte";

    let questionPromise = getQuestion(questionID);

    let answers = [];
    let newBatchOfAnswers = [];
    let offsetNumber = 1;
    let resolved = false;

    // TODO onMount open eventsource, onDestroy close it
    const eventSource = new EventSource("/api/q-a-updates");
    eventSource.onmessage = (event) => {
        if (event.data === "AnswerAdded") {
            console.log(event.data);
            handleAddedAnswer();
        };
    };

    const loadFirstAnswers = async () => {
        newBatchOfAnswers = await getCourseQuestionAnswers(questionID, 0);
        console.log(newBatchOfAnswers);
        resolved = true;
    };

    const handleAddedAnswer = () => {
        answers = [];
        newBatchOfAnswers = [];
        resolved = false;
        offsetNumber = 1;
        loadFirstAnswers();
    };

    const loadMoreAnswers = async () => {
        console.log("Now more answers should be loaded");
        await new Promise(r => setTimeout(r, 1000));
        newBatchOfAnswers = await getCourseQuestionAnswers(questionID, offsetNumber);
        offsetNumber++;
    };

    onMount( async () => {
		// load first batch onMount
        loadFirstAnswers();
	})

    $: answers = [
		...answers,
        ...newBatchOfAnswers
    ];

</script>

{#await questionPromise}
    <p>Loading question</p>
{:then questions}
<div class="mb-4 pb-20 p-6 bg-white border border-gray-200 rounded-lg shadow">
    <span class="float-right text-sm">Posted on: {questions[0].posted}</span>
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">{questions[0].title}</h5>
    <p class="font-normal text-gray-700">{questions[0].question_content}</p>
    <Upvote isQuestion={true} q_a_id={questionID}/>
</div>
<!-- Removed on:change{handleAddedAnswer} because it is updated by SSE -->
<span class="float-right p-2 border border-gray-300"><a href={"/course-" + questions[0].course_id}>Go back to question list</a></span>
<PostAnswerButtonModal questionID={questionID} />
{/await}

{#each answers as answer}
    <Answer answerID={answer.id} answerTitle={answer.title} answerContent= {answer.answer_content} answerDate={answer.posted}/>
{/each}
{#if answers.length == 0}
    <p>Looks like there are no answers in this course yet. Wait a moment for some autogenerated ones!</p>
{/if}

{#if resolved}
    <p use:viewport
        on:enterViewport={() => loadMoreAnswers()}
        on:exitViewport={() => console.log('exit viewport!')}
    ></p>
{/if}