<script>
    export let questionID;
    import Answer from "./Answer.svelte";
    import PostAnswerButtonModal from "./PostAnswerButtonModal.svelte";
    import { getCourseQuestionAnswers, getQuestion } from "../services/APIService";
    let questionPromise = getQuestion(questionID);
    let answersPromise = getCourseQuestionAnswers(questionID);

    const handleAddedAnswer = () => {
        // TODO Decide if reload all answers, load answer by ID or jut pass answer props through Event
        console.log("AnswerList.svelte has gotten an update!");
        answersPromise = getCourseQuestionAnswers(questionID);
    };

    // TODO Reuse the Question.svelte component instead of the <div> with spans?
</script>

{#await questionPromise}
    <p>Loading question</p>
{:then questions}
<span class="float-right p-2 border border-gray-300"><a href={"/course-" + questions[0].course_id}>Go back to question list</a></span>
<div class="mb-4 pb-20 p-6 bg-white border border-gray-200 rounded-lg shadow">
    <span class="float-right text-sm">Upvotes: 4</span>
    <span class="float-right text-sm mr-2">Answers: 5</span>
    <span class="float-right text-sm mr-2">Posted on: {questions[0].posted}</span>
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">{questions[0].title}</h5>
    <p class="font-normal text-gray-700">{questions[0].question_content}</p>
</div>
<PostAnswerButtonModal on:change={handleAddedAnswer} courseNumber={questions[0].course_id} questionID={questionID} />
{/await}

{#await answersPromise}
    <p>Loading answers</p>
{:then answers}
    {#if answers.length === 0}
        <p>There are no answers yet. Check back soon for some autogenerated ones!</p>
    {/if}
    {#each answers as answer}
        <Answer answerTitle={answer.title} answerContent= {answer.answer_content} answerDate={answer.posted}/>
    {/each}
{/await}