<script>
    export let questionID;
    import Answer from "./Answer.svelte";
    import { getCourseQuestionAnswers, getQuestion } from "../services/APIService";
    let questionPromise = getQuestion(questionID);
    let answersPromise = getCourseQuestionAnswers(questionID);

    // TODO Reuse the Question.svelte component instead of the <div> with spans?
</script>

{#await questionPromise}
    <p>Loading answers</p>
{:then questions}
<div class="mb-4 pb-20 p-6 bg-white border border-gray-200 rounded-lg shadow">
    <span class="float-right text-sm">Upvotes: 4</span>
    <span class="float-right text-sm mr-2">Answers: 5</span>
    <span class="float-right text-sm mr-2">Posted on: {questions[0].posted}</span>
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">{questions[0].title}</h5>
    <p class="font-normal text-gray-700">{questions[0].question_content}</p>
</div>
{/await}

{#await answersPromise}
    <p>Loading answers</p>
{:then answers}
    {#if answers.length === 0}
        <p>There are no answers yet. Check back soon for some autogenerated ones!</p>
    {/if}
    {#each answers as answer}
        <Answer answer={answer.title + " " + answer.answer_content}/>
    {/each}
{/await}